export default [
  "Ayo kita beli jajan",
  "Ke asrama",
  "Panas banget",
  "Malah ngambek",
  "Kecilkan suaramu",
  "Tutupkan pintu",
  "Ambilkan itu",
  "Aku mau baca di mimbar",
  "Siapa baca hadits?",
  "Lupa naronya di mana",
  "Matikan lampunya",
  "Izin ambil sandal",
  "Hapalanku kurang lancar",
  "Siapa yang suruh buka air?",
  "Ayo kita tidur. Aku udah ngantuk",
  "Warung depan buka kah?",
  "Nitip belikan ya",
  "Pinjam buku",
  "Bajuku masih baal",
  "Kecilin kipasnya",
  "Coba ketok tandanya",
  "Minta tolong bawakan",
  "Aku nggak suka nasi",
  "Ambilkan mejaku nah",
  "Jangan ribut pang. Nyaring betul",
  "Aku mau tidur dulu",
  "Memang betulan?",
  "Jangan nyalakan lampu. Panas",
  "Siapa imam?",
  "Izin ambil buku kecil",
  "Nggak usah kayak gitu",
  "Kejar dia",
  "Kamu punya kantong nggak?",
  "Izin minum air",
  "Jilbabku lagi dicuci (putra: baju)",
  "Kamu mandi duluan ya",
  "Pakai kasur kah nggak?",
  "Makanannya belum diambil kah?",
  "Bagi-bagi dong",
  "Saya sangat mengantuk",
  "Sabar sedikit coba",
  "Gulungkan kabelnya",
  "Kamu mau beli apa?",
  "Gantungan bajuku kurang eh",
  "Harus banyak minum air putih",
  "Siapa yang piket?",
  "Pinjam pulpen",
  "Eh, masih lama kah mandinya?",
  "Makan siangnya apa?",
  "Aku mau beli es dan gorengan",
  "Pembalap",
  "Pakai pewangi apa kamu?",
  "Jam berapa sekarang?",
  "Di ayunan",
  "Aku mau minta fotokan titipanku",
  "Bajumu bau",
  "Aku mau ngasih temanku",
  "Mandinya jangan lama-lama ya",
  "Piketi kamarnya",
  "Harinya mendung, ambil jemuran",
  "Pinjam pulpen",
  "Acil buka nah",
  "Nggak usah ganggu pang",
  "Aku mau ke WC",
  "Ada orang gila",
  "Aku mau minum",
  "Cucuk obat nyamuknya",
  "Kapan kamu beli itu?",
  "Coba lihat sini",
  "Bagi parfum",
  "Jangan tidur",
  "Aku kedinginan",
  "Aku mau adzan",
  "Kamu tas baru ya?",
  "Aku mau tidur",
  "Kamu mau ke mana?",
  "Mau nitip pang",
  "Siapa yang piket hari ini?",
  "Hmmm… Bau apa ni?",
  "Tolong kembalikan pakunya",
  "Jangan tanya aku",
  "Aku mau ambil buku",
  "Jemurannya penuh bah",
  "Jilbab putihku kotor banget (putra: celana)",
  "Kapan kamu makan?",
  "Ngantri napa",
  "Yang ambil makan, bawa termos",
  "Kecilkan kipasnya",
  "Mau pergi ke mana?",
  "Tolong nyalakan kipasnya",
  "Izin pergi ke asrama",
  "Ganti bajumu",
  "Belum disapu",
  "Belum dipel",
  "Siapa yang adzan?",
  "Aku kepanasan",
  "Boleh cucian kah?",
  "Mau nitip es apa?",
  "Itu nah atas lemarinya dirapikan",
  "Tolong angkatkan galon",
  "Aku mau ke Jawa",
  "Matikan airnya ya",
  "Kamu sudah sampai mana?",
  "Aku mau main pingpong",
  "Mau pakai baju warna apa?",
  "Warung acil udah buka",
  "Cucian, cucian..",
  "Panas kali hari ini…",
  "Apa makanannya?",
  "Ambil meja",
  "Mana orangnya?",
  "Keluarkan hijabnya",
  "Aku mau ngapain ya?",
  "Siapa adzan Dzuhur ini?",
  "Jam berapa adzan?",
  "Siapa khatib?",
  "Apakah kamu sedang puasa?",
  "Diam. Ada yang lagi tidur",
  "Panco yok",
  "Siapa hiwar?",
  "Tutup pintu masjid",
  "Ih, aku belum lipatan baju",
  "Aku mau cerita",
  "Weh, ayo kita makan",
  "Temanin aku di kamar",
  "Jangan ngobrol",
  "Cucukkan pang Sanyo",
  "Sembarang aja",
  "Capek betul",
  "Izin ke WC",
  "Capeknya, asliii…",
  "Jangan ribut kalau dimarahin",
  "Ada yang kelahi",
  "Ih, airnya kotor",
  "Eh hari Ahad main ke Alba kah?",
  "Mana yang lain?",
  "Balapan di mana?",
  "Aku mau nitip dong",
  "Tunggu sebentar",
  "Kamu sudah selesai?",
  "Matikan lampunya. Aku mau tidur",
  "Tes suara mic di gudang yok",
  "Mau beli bakso",
  "Bekas makan siapa ini?",
  "Eh temenin aku dong",
  "Ayo lari",
  "Lihat ada banyak pekerja bangunan",
  "Jangan malas piket",
  "Karpetnya dilipat",
  "Ambilkan seperangkat alat tidurku, tolong",
  "Pake baju samaan yok",
  "Aku mau imam",
  "Sholat sunnah dulu",
  "Siapa imam?",
  "Matiin kipasnya",
  "Siapa yang imam malam ini?",
  "Motormu bagus betul",
  "Aduh capek banget sih",
  "Ambilkan meja",
  "Jangan gantung baju di jendela. Pengap",
  "Tidur di atas",
  "Aku lagi capek banget",
  "Matiin lampunya",
  "Masih lama kah?",
  "Nyalakan kipasnya pang",
  "Baca Qurannya",
  "Siapa yang adzan Dzuhur ini?",
  "Kapan kamu jemuran?",
  "Tukaran kah?",
  "Siapa adzan?",
  "Jangan lupa ganti baju",
  "Nggak sah itu",
  "Tolong matikan kipas",
  "Minta air nah",
  "Ada yang nangis",
  "Jangan lupa",
  "Matikan lampunya nanti",
  "Kagetnya pang",
  "Main yuk",
  "Bagaimana Kak?",
  "Aku mau adzan",
  "Hambalnya kotor",
  "Aku mau ke bawah. Ada yang mau nitip?",
  "Aku mau juga. Boleh nggak?",
  "Deras sekali kipasnya",
  "Susun shaffnya",
  "Siapa ceramah?",
  "Rapikan shaffnya",
  "Tolong ambilkan tasku sama buku",
  "Saya pengen BAB",
  "Minta tolong ambilkan dong",
  "Kerja bagus",
  "Mana gelasku",
  "Jangan mainan",
  "Lucu sekali",
  "Beli yok",
  "Ini punyamu",
  "Kembalikan sajadah",
  "Woi, jangan berisik",
];
